import React from "react";
import { ShieldCheck, ExternalLink, Scale, FileText, Sparkles } from "lucide-react";

export const Footer: React.FC = () => {
  return (
    <footer className="w-full border-t border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-950 mt-16 text-slate-600 dark:text-slate-400 text-xs">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-10">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          
          {/* Project Identity */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <ShieldCheck className="h-5 w-5 text-emerald-800 dark:text-emerald-400" />
              <span className="font-bold text-slate-900 dark:text-white font-serif text-sm">
                IP-SAKTI Sahayak
              </span>
            </div>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed mb-3">
              An evidence-grounded Retrieval-Augmented Generation (RAG) assistant empowering Ayurveda innovators, researchers, startups, and entrepreneurs with authoritative IPR and regulatory intelligence.
            </p>
            <div className="inline-flex items-center gap-1.5 rounded-md bg-emerald-50 dark:bg-emerald-950/40 px-2.5 py-1 text-[11px] font-medium text-emerald-800 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-900">
              <Sparkles className="h-3.5 w-3.5" />
              <span>Smart India Hackathon Initiative</span>
            </div>
          </div>

          {/* Statutory Knowledge Sources */}
          <div>
            <h4 className="font-semibold text-slate-900 dark:text-white text-xs uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <FileText className="h-4 w-4 text-emerald-700" />
              Authoritative Frameworks
            </h4>
            <ul className="space-y-1.5 text-slate-600 dark:text-slate-400">
              <li className="flex items-start gap-1.5">
                <span className="text-emerald-600 font-bold">•</span>
                <span>The Patents Act, 1970 & Patent Rules, 2003</span>
              </li>
              <li className="flex items-start gap-1.5">
                <span className="text-emerald-600 font-bold">•</span>
                <span>Guidelines for Examination of Ayush-Related Inventions (CGPDTM)</span>
              </li>
              <li className="flex items-start gap-1.5">
                <span className="text-emerald-600 font-bold">•</span>
                <span>Traditional Knowledge Digital Library (TKDL) Prior Art Standards</span>
              </li>
              <li className="flex items-start gap-1.5">
                <span className="text-emerald-600 font-bold">•</span>
                <span>FSSAI Ayurveda Aahara Regulations, 2022</span>
              </li>
              <li className="flex items-start gap-1.5">
                <span className="text-emerald-600 font-bold">•</span>
                <span>Biological Diversity Act, 2002 & ABS Guidelines</span>
              </li>
            </ul>
          </div>

          {/* Legal Disclaimer Box */}
          <div>
            <h4 className="font-semibold text-slate-900 dark:text-white text-xs uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <Scale className="h-4 w-4 text-amber-700" />
              Statutory Disclaimer
            </h4>
            <div className="p-3 bg-amber-50/70 dark:bg-amber-950/20 border border-amber-200/80 dark:border-amber-900/60 rounded-lg text-slate-700 dark:text-slate-300 leading-relaxed text-[11px]">
              Information generated by IP-SAKTI Sahayak is synthesized using retrieval-augmented artificial intelligence from official statutory publications and guidelines. It is intended strictly for general regulatory and informational guidance and does not constitute formal legal counsel or an official patent determination.
            </div>
          </div>

        </div>

        <div className="border-t border-slate-200 dark:border-slate-800 mt-8 pt-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-[11px] text-slate-500">
          <p>© 2026 IP-SAKTI Sahayak. Grounded RAG with BGE-M3, pgvector & Qwen3.</p>
          <div className="flex items-center gap-4">
            <span className="inline-flex items-center gap-1">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
              5,842 Knowledge Chunks Indexed
            </span>
            <span className="inline-flex items-center gap-1">
              <span className="h-1.5 w-1.5 rounded-full bg-blue-500" />
              35 Statutory Documents
            </span>
          </div>
        </div>
      </div>
    </footer>
  );
};
