import React from "react";
import { ShieldCheck, ExternalLink, Scale, FileText, Sparkles } from "lucide-react";

export const Footer: React.FC = () => {
  return (
    <footer className="w-full border-t border-[#1a2e24] bg-[#0e1d17] mt-16 text-[#9ca3af] text-xs">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          
          {/* Project Identity */}
          <div>
            <div className="flex items-center gap-2.5 mb-3">
              <div className="h-7 w-7 rounded bg-[#152e22] border border-[#234534] flex items-center justify-center text-[#10b981]">
                <ShieldCheck className="h-4 w-4" />
              </div>
              <span className="font-bold text-white font-serif text-sm">
                IP-SAKTI Sahayak
              </span>
            </div>
            <p className="text-[#9ca3af] leading-relaxed mb-4 text-xs">
              An evidence-grounded Retrieval-Augmented Generation (RAG) assistant empowering Ayurveda innovators, researchers, startups, and entrepreneurs with authoritative IPR and regulatory intelligence.
            </p>
            <div className="inline-flex items-center gap-1.5 rounded-full bg-[#152e22] px-3 py-1 text-[11px] font-medium text-[#85f8c4] border border-[#234534]">
              <Sparkles className="h-3.5 w-3.5 text-[#10b981]" />
              <span>Smart India Hackathon Initiative</span>
            </div>
          </div>

          {/* Statutory Knowledge Sources */}
          <div>
            <h4 className="font-semibold text-white text-xs uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <FileText className="h-4 w-4 text-[#10b981]" />
              Authoritative Frameworks
            </h4>
            <ul className="space-y-2 text-[#9ca3af]">
              <li className="flex items-start gap-2">
                <span className="text-[#10b981] font-bold">•</span>
                <span>The Patents Act, 1970 &amp; Patent Rules, 2003</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#10b981] font-bold">•</span>
                <span>Guidelines for Examination of Ayush-Related Inventions (CGPDTM)</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#10b981] font-bold">•</span>
                <span>Traditional Knowledge Digital Library (TKDL) Prior Art Standards</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#10b981] font-bold">•</span>
                <span>FSSAI Ayurveda Aahara Regulations, 2022</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#10b981] font-bold">•</span>
                <span>Biological Diversity Act, 2002 &amp; ABS Guidelines</span>
              </li>
            </ul>
          </div>

          {/* Legal Disclaimer Box */}
          <div>
            <h4 className="font-semibold text-white text-xs uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <Scale className="h-4 w-4 text-[#f59e0b]" />
              Statutory Disclaimer
            </h4>
            <div className="p-3.5 bg-[#15241d] border border-[#233b2f] rounded-xl text-[#d1d5db] leading-relaxed text-[11px]">
              Information generated by IP-SAKTI Sahayak is synthesized using retrieval-augmented artificial intelligence from official statutory publications and guidelines. It is intended strictly for general regulatory and informational guidance and does not constitute formal legal counsel or an official patent determination.
            </div>
          </div>

        </div>

        <div className="border-t border-[#1a2e24] mt-10 pt-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-[11px] text-[#6b7280]">
          <p>© 2026 IP-SAKTI Sahayak. Grounded RAG with BGE-M3, pgvector &amp; Qwen3.</p>
          <div className="flex items-center gap-4">
            <span className="inline-flex items-center gap-1 text-[#9ca3af]">
              <span className="h-1.5 w-1.5 rounded-full bg-[#10b981]" />
              5,842 Knowledge Chunks Indexed
            </span>
            <span className="inline-flex items-center gap-1 text-[#9ca3af]">
              <span className="h-1.5 w-1.5 rounded-full bg-[#3b82f6]" />
              35 Statutory Documents
            </span>
          </div>
        </div>
      </div>
    </footer>
  );
};
