export interface StructuredPoint {
  title?: string;
  content: string;
  isImportant?: boolean;
}

export interface PlainTermExplanation {
  term: string;
  simpleMeaning: string;
}

export interface StructuredAnswer {
  summary: string;
  points: StructuredPoint[];
  termsExplained: PlainTermExplanation[];
  followUpQuestions?: string[];
  statutoryConclusion?: string;
}

// Plain-English explanations for complex legal/statutory terminology
const LEGAL_TERMS_DICTIONARY: Record<string, string> = {
  "section 3(p)": "Section 3(p) bans patenting known traditional knowledge or Ayurvedic remedies already described in ancient texts.",
  "section 3(e)": "Section 3(e) bans patenting a simple mixture of known herbs unless you prove a synergistic effect (they work significantly better together than alone).",
  "section 3(d)": "Section 3(d) bans patenting new forms or slight modifications of known substances unless they show significantly higher therapeutic efficacy.",
  "tkdl": "TKDL (Traditional Knowledge Digital Library) is India's official database of ancient Ayurvedic formulations used by patent examiners to check if a formula is already documented.",
  "nba": "National Biodiversity Authority (NBA) requires mandatory prior approval before filing a patent for any product utilizing Indian herbs or biological resources.",
  "prior art": "Prior Art refers to any public information, ancient text, or past patent that already describes the idea before your filing date.",
  "synergistic": "Synergistic effect means the ingredients cooperate to produce a stronger, non-obvious medical effect than their simple addition.",
  "admixture": "A mere admixture is simply mixing known ingredients together without creating a new chemical or clinical advancement.",
  "ayurveda aahara": "Ayurveda Aahara regulations govern food and dietary supplements prepared according to classical Ayurvedic treatises, overseen by FSSAI and the Ministry of Ayush.",
  "novelty": "Novelty means your specific extraction method, purified fraction, or formulation has never been published or used anywhere in the world.",
};

const MEDICINE_DEFAULT_FOLLOW_UPS = [
  "Classical Treatises: Is this combination or formulation already documented in classical Ayurvedic texts (such as Charaka Samhita, Sushruta Samhita, or Ayurvedic Formulary of India) or TKDL?",
  "Synergistic Efficacy (Section 3(e)): Do you have comparative experimental or clinical data showing synergistic therapeutic enhancement beyond a simple herb mixture?",
  "Novel Process / Delivery (Section 3(d)): Does your product feature an inventive extraction technique, isolated bio-active fraction, or novel drug delivery system (e.g. nano-carriers)?",
  "Biodiversity Clearance (Section 6, BD Act): Are the herbal ingredients obtained from Indian biological resources requiring prior National Biodiversity Authority (NBA Form 1) approval?",
];

export function structureAnswer(rawAnswer: string, query?: string): StructuredAnswer {
  if (!rawAnswer) {
    return { summary: "", points: [], termsExplained: [], followUpQuestions: [] };
  }

  // Remove the boilerplate disclaimer if repeated at the end of the answer text
  let cleanText = rawAnswer
    .replace(/This information is for general guidance only and is not legal advice\.?/gi, "")
    .trim();

  // Extract follow-up questions if generated by LLM
  let followUpQuestions: string[] = [];
  const followUpMatch = cleanText.match(/###?\s*Follow-up Questions[^:]*:\s*([\s\S]*?)$/i);
  if (followUpMatch && followUpMatch[1]) {
    const rawFollowUps = followUpMatch[1].trim();
    const lines = rawFollowUps.split(/\n+/).map((l) => l.replace(/^[-*•\d+.]\s+/, "").trim()).filter(Boolean);
    if (lines.length > 0) {
      followUpQuestions = lines;
      // Strip follow-up section from main answer text to avoid duplicate rendering
      cleanText = cleanText.replace(followUpMatch[0], "").trim();
    }
  }

  // Split by double newlines first
  const rawParagraphs = cleanText
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter(Boolean);

  if (rawParagraphs.length === 0) {
    return { summary: cleanText, points: [], termsExplained: [], followUpQuestions };
  }

  // Use first paragraph or sentence as executive summary
  const summary = rawParagraphs[0];
  const remaining = rawParagraphs.slice(1);

  const points: StructuredPoint[] = [];

  // Check if remaining paragraphs contain bullet points or numbered lists
  for (const para of remaining) {
    const lines = para.split(/\n+/).map((l) => l.trim()).filter(Boolean);

    // If multiple lines starting with bullets or numbers
    const isList = lines.every((l) => /^[-*•\d+.]\s+/.test(l));

    if (isList && lines.length > 1) {
      for (const line of lines) {
        const cleanedLine = line.replace(/^[-*•\d+.]\s+/, "");
        points.push({
          content: cleanedLine,
        });
      }
    } else {
      const lower = para.toLowerCase();
      let title: string | undefined = undefined;

      if (lower.includes("section 3(p)") || lower.includes("traditional knowledge")) {
        title = "Traditional Knowledge & Section 3(p) Bar";
      } else if (lower.includes("section 3(e)") || lower.includes("synerg") || lower.includes("admixture")) {
        title = "Synergistic Efficacy & Section 3(e) Requirement";
      } else if (lower.includes("section 3(d)") || lower.includes("efficacy")) {
        title = "Therapeutic Enhancement (Section 3(d))";
      } else if (lower.includes("section 3") || lower.includes("exclusion") || lower.includes("cannot be considered")) {
        title = "Statutory Exclusions & Legal Restrictions";
      } else if (lower.includes("prior art") || lower.includes("tkdl")) {
        title = "Prior Art Search & TKDL Verification";
      } else if (lower.includes("requirement") || lower.includes("patentability") || lower.includes("novelty") || lower.includes("inventive step")) {
        title = "Core Patentability Requirements (Novelty & Non-Obviousness)";
      } else if (lower.includes("process") || lower.includes("extraction") || lower.includes("method")) {
        title = "Novel Extraction & Process Claims";
      } else if (lower.includes("nba") || lower.includes("biodiversity") || lower.includes("biological diversity")) {
        title = "Biological Diversity Act (NBA Clearance)";
      } else if (lower.includes("fssai") || lower.includes("aahara") || lower.includes("food")) {
        title = "Ayurveda Aahara & Dietary Standards";
      }

      points.push({
        title,
        content: para,
      });
    }
  }

  // If there were no remaining paragraphs (single long paragraph), break it intelligently by sentences
  if (points.length === 0 && summary.length > 200) {
    const sentences = summary.match(/[^.!?]+[.!?]+(\s+\[Source\s+\d+[^\]]*\])?/g) || [summary];
    if (sentences.length > 1) {
      const parsedSummary = sentences[0].trim();
      const parsedPoints = sentences.slice(1).map((s, idx) => ({
        title: `Key Detail ${idx + 1}`,
        content: s.trim(),
      }));

      // Detect terms in text
      const fullText = (summary + " " + rawAnswer).toLowerCase();
      const termsExplained: PlainTermExplanation[] = [];
      for (const [key, val] of Object.entries(LEGAL_TERMS_DICTIONARY)) {
        if (fullText.includes(key)) {
          termsExplained.push({ term: key.toUpperCase(), simpleMeaning: val });
        }
      }

      // Check for medicine query follow-ups
      if (followUpQuestions.length === 0) {
        const checkMed = (summary + " " + (query || "")).toLowerCase();
        if (/medicine|formulation|herb|drug|extract|ashwagandha|turmeric|curcumin|neem|tulsi|composition|remedy|synerg/.test(checkMed)) {
          followUpQuestions = MEDICINE_DEFAULT_FOLLOW_UPS;
        }
      }

      return {
        summary: parsedSummary,
        points: parsedPoints,
        termsExplained: termsExplained.slice(0, 4),
        followUpQuestions,
      };
    }
  }

  // Detect which legal terms are present in the answer to provide simple plain-English explanations
  const fullText = (summary + " " + rawAnswer).toLowerCase();
  const termsExplained: PlainTermExplanation[] = [];
  for (const [key, val] of Object.entries(LEGAL_TERMS_DICTIONARY)) {
    if (fullText.includes(key)) {
      termsExplained.push({ term: key.toUpperCase(), simpleMeaning: val });
    }
  }

  // Check for medicine query follow-ups
  if (followUpQuestions.length === 0) {
    const checkMed = (summary + " " + (query || "")).toLowerCase();
    if (/medicine|formulation|herb|drug|extract|ashwagandha|turmeric|curcumin|neem|tulsi|composition|remedy|synerg/.test(checkMed)) {
      followUpQuestions = MEDICINE_DEFAULT_FOLLOW_UPS;
    }
  }

  return {
    summary,
    points,
    termsExplained: termsExplained.slice(0, 4),
    followUpQuestions,
  };
}
