export interface StructuredPoint {
  title?: string;
  content: string;
  isImportant?: boolean;
}

export interface PlainTermExplanation {
  term: string;
  simpleMeaning: string;
}

export interface StructuredAnswer {
  summary: string;
  points: StructuredPoint[];
  termsExplained: PlainTermExplanation[];
  followUpQuestions?: string[];
  statutoryConclusion?: string;
}

// Plain-English explanations for complex legal/statutory terminology
const LEGAL_TERMS_DICTIONARY: Record<string, string> = {
  "section 3(p)": "Section 3(p) bans patenting known traditional knowledge or Ayurvedic remedies already described in ancient texts.",
  "section 3(e)": "Section 3(e) bans patenting a simple mixture of known herbs unless you prove a synergistic effect (they work significantly better together than alone).",
  "section 3(d)": "Section 3(d) bans patenting new forms or slight modifications of known substances unless they show significantly higher therapeutic efficacy.",
  "tkdl": "TKDL (Traditional Knowledge Digital Library) is India's official database of ancient Ayurvedic formulations used by patent examiners to check if a formula is already documented.",
  "nba": "National Biodiversity Authority (NBA) requires mandatory prior approval before filing a patent for any product utilizing Indian herbs or biological resources.",
  "prior art": "Prior Art refers to any public information, ancient text, or past patent that already describes the idea before your filing date.",
  "synergistic": "Synergistic effect means the ingredients cooperate to produce a stronger, non-obvious medical effect than their simple addition.",
  "admixture": "A mere admixture is simply mixing known ingredients together without creating a new chemical or clinical advancement.",
  "ayurveda aahara": "Ayurveda Aahara regulations govern food and dietary supplements prepared according to classical Ayurvedic treatises, overseen by FSSAI and the Ministry of Ayush.",
  "novelty": "Novelty means your specific extraction method, purified fraction, or formulation has never been published or used anywhere in the world.",
};

const MEDICINE_DEFAULT_FOLLOW_UPS = [
  "Classical Treatises: Is this combination or formulation already documented in classical Ayurvedic texts (such as Charaka Samhita, Sushruta Samhita, or Ayurvedic Formulary of India) or TKDL?",
  "Synergistic Efficacy (Section 3(e)): Do you have comparative experimental or clinical data showing synergistic therapeutic enhancement beyond a simple herb mixture?",
  "Novel Process / Delivery (Section 3(d)): Does your product feature an inventive extraction technique, isolated bio-active fraction, or novel drug delivery system (e.g. nano-carriers)?",
  "Biodiversity Clearance (Section 6, BD Act): Are the herbal ingredients obtained from Indian biological resources requiring prior National Biodiversity Authority (NBA Form 1) approval?",
];

export function structureAnswer(rawAnswer: string, query?: string): StructuredAnswer {
  if (!rawAnswer) {
    return { summary: "", points: [], termsExplained: [], followUpQuestions: [] };
  }

  // Remove the boilerplate disclaimer if repeated at the end of the answer text
  let cleanText = rawAnswer
    .replace(/This information is for general guidance only and is not legal advice\.?/gi, "")
    // Strip standalone horizontal rule lines (---, ***, ___)
    .replace(/^\s*[-*_]{3,}\s*$/gm, "")
    .trim();

  // Extract follow-up questions if generated by LLM
  let followUpQuestions: string[] = [];
  const followUpMatch = cleanText.match(/###?\s*Follow-up Questions[^:]*:\s*([\s\S]*?)$/i);
  if (followUpMatch && followUpMatch[1]) {
    const rawFollowUps = followUpMatch[1].trim();
    const lines = rawFollowUps.split(/\n+/).map((l) => l.replace(/^[-*•\d+.]\s+/, "").trim()).filter(Boolean);
    if (lines.length > 0) {
      followUpQuestions = lines;
      cleanText = cleanText.replace(followUpMatch[0], "").trim();
    }
  }

  // Split by double newlines into raw blocks
  const rawParagraphs = cleanText
    .split(/\n{2,}/)
    .map((p) => p.trim())
    // Filter out empty or delimiter-only blocks
    .filter((p) => p.length > 0 && !/^[-*_#\s]+$/.test(p));

  if (rawParagraphs.length === 0) {
    return { summary: cleanText, points: [], termsExplained: [], followUpQuestions };
  }

  let summary = "";
  const candidateBlocks: { raw: string; sectionHeader?: string }[] = [];
  let currentSection = "";

  for (const p of rawParagraphs) {
    // Check if the block is purely a markdown section header e.g. "### **Statutory Guidance**"
    const headerMatch = p.match(/^#{1,6}\s*(?:\*\*)?([^*\n]+?)(?:\*\*)?\s*$/);
    if (headerMatch && headerMatch[1]) {
      currentSection = headerMatch[1].replace(/\*\*/g, "").trim();
      continue;
    }

    if (!summary) {
      // Clean leading markdown headers from summary if any
      summary = p.replace(/^#{1,6}\s*/, "").replace(/^\*\*(.*?)\*\*\s*:\s*/, "$1: ").trim();
    } else {
      candidateBlocks.push({ raw: p, sectionHeader: currentSection });
    }
  }

  const points: StructuredPoint[] = [];

  for (const item of candidateBlocks) {
    let text = item.raw.trim();
    if (!text || /^[-*_#\s]+$/.test(text)) continue;

    const lines = text.split(/\n+/).map((l) => l.trim()).filter(Boolean);

    // If multiple lines all starting with bullets or numbers
    const isPureList = lines.length > 1 && lines.every((l) => /^[-*•\d+.]\s+/.test(l));

    if (isPureList) {
      for (const line of lines) {
        const cleanedLine = line.replace(/^[-*•\d+.]\s+/, "").trim();
        if (cleanedLine && !/^[-*_#\s]+$/.test(cleanedLine)) {
          points.push({
            content: cleanedLine,
          });
        }
      }
    } else {
      let extractedTitle: string | undefined = undefined;

      // Check if first line is a title e.g.
      // **1. Title Text**\nRemaining...
      // 1. **Title Text**\nRemaining...
      // ### Title Text\nRemaining...
      const firstLine = lines[0];
      const hasHeadingSyntax =
        /^(?:#{1,6}\s*|\*\*(?:\d+[\.\)]\s*)?|(?:\d+[\.\)]\s*)\*\*)/.test(firstLine);

      if (hasHeadingSyntax && lines.length > 1) {
        const cleanTitle = firstLine
          .replace(/\*\*/g, "")
          .replace(/^#{1,6}\s*/, "")
          .replace(/:\s*$/, "")
          .trim();

        if (cleanTitle.length >= 3 && cleanTitle.length <= 160) {
          extractedTitle = cleanTitle;
          text = lines.slice(1).join("\n").trim();
        }
      }

      // Keyword-based fallback for titles if no explicit heading line was extracted
      if (!extractedTitle) {
        const lower = ((item.sectionHeader || "") + " " + text).toLowerCase();
        if (lower.includes("section 3(p)") || lower.includes("traditional knowledge")) {
          extractedTitle = "Traditional Knowledge & Section 3(p) Bar";
        } else if (lower.includes("section 3(e)") || lower.includes("synerg") || lower.includes("admixture")) {
          extractedTitle = "Synergistic Efficacy & Section 3(e) Requirement";
        } else if (lower.includes("section 3(d)") || lower.includes("efficacy")) {
          extractedTitle = "Therapeutic Enhancement (Section 3(d))";
        } else if (lower.includes("section 3") || lower.includes("exclusion") || lower.includes("cannot be considered")) {
          extractedTitle = "Statutory Exclusions & Legal Restrictions";
        } else if (lower.includes("prior art") || lower.includes("tkdl")) {
          extractedTitle = "Prior Art Search & TKDL Verification";
        } else if (lower.includes("requirement") || lower.includes("patentability") || lower.includes("novelty") || lower.includes("inventive step")) {
          extractedTitle = "Core Patentability Requirements (Novelty & Non-Obviousness)";
        } else if (lower.includes("process") || lower.includes("extraction") || lower.includes("method")) {
          extractedTitle = "Novel Extraction & Process Claims";
        } else if (lower.includes("nba") || lower.includes("biodiversity") || lower.includes("biological diversity")) {
          extractedTitle = "Biological Diversity Act (NBA Clearance)";
        } else if (lower.includes("fssai") || lower.includes("aahara") || lower.includes("food")) {
          extractedTitle = "Ayurveda Aahara & Dietary Standards";
        } else if (item.sectionHeader) {
          extractedTitle = item.sectionHeader;
        }
      }

      // Ensure content is not blank or pure markdown delimiter
      if (text && !/^[-*_#\s]+$/.test(text)) {
        points.push({
          title: extractedTitle,
          content: text,
        });
      }
    }
  }

  // Fallback: If no points extracted from single multi-sentence summary
  if (points.length === 0 && summary.length > 200) {
    const sentences = summary.match(/[^.!?]+[.!?]+(\s+\[Source\s+\d+[^\]]*\])?/g) || [summary];
    if (sentences.length > 1) {
      const parsedSummary = sentences[0].trim();
      const parsedPoints = sentences.slice(1).map((s, idx) => ({
        title: `Key Detail ${idx + 1}`,
        content: s.trim(),
      }));

      const fullText = (summary + " " + rawAnswer).toLowerCase();
      const termsExplained: PlainTermExplanation[] = [];
      for (const [key, val] of Object.entries(LEGAL_TERMS_DICTIONARY)) {
        if (fullText.includes(key)) {
          termsExplained.push({ term: key.toUpperCase(), simpleMeaning: val });
        }
      }

      if (followUpQuestions.length === 0) {
        const checkMed = (summary + " " + (query || "")).toLowerCase();
        if (/medicine|formulation|herb|drug|extract|ashwagandha|turmeric|curcumin|neem|tulsi|composition|remedy|synerg/.test(checkMed)) {
          followUpQuestions = MEDICINE_DEFAULT_FOLLOW_UPS;
        }
      }

      return {
        summary: parsedSummary,
        points: parsedPoints,
        termsExplained: termsExplained.slice(0, 4),
        followUpQuestions,
      };
    }
  }

  // Detect legal terms for plain English dictionary
  const fullText = (summary + " " + rawAnswer).toLowerCase();
  const termsExplained: PlainTermExplanation[] = [];
  for (const [key, val] of Object.entries(LEGAL_TERMS_DICTIONARY)) {
    if (fullText.includes(key)) {
      termsExplained.push({ term: key.toUpperCase(), simpleMeaning: val });
    }
  }

  if (followUpQuestions.length === 0) {
    const checkMed = (summary + " " + (query || "")).toLowerCase();
    if (/medicine|formulation|herb|drug|extract|ashwagandha|turmeric|curcumin|neem|tulsi|composition|remedy|synerg/.test(checkMed)) {
      followUpQuestions = MEDICINE_DEFAULT_FOLLOW_UPS;
    }
  }

  return {
    summary,
    points,
    termsExplained: termsExplained.slice(0, 4),
    followUpQuestions,
  };
}
