import { SupportedLanguage } from "@/types/api";

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  {
    code: "en",
    indictrans_code: "eng_Latn",
    display_name: "English",
    native_name: "English",
    script: "Latin",
    enabled: true,
  },
  {
    code: "hi",
    indictrans_code: "hin_Deva",
    display_name: "Hindi",
    native_name: "हिन्दी",
    script: "Devanagari",
    enabled: true,
  },
  {
    code: "ta",
    indictrans_code: "tam_Taml",
    display_name: "Tamil",
    native_name: "தமிழ்",
    script: "Tamil",
    enabled: true,
  },
  {
    code: "te",
    indictrans_code: "tel_Telu",
    display_name: "Telugu",
    native_name: "తెలుగు",
    script: "Telugu",
    enabled: true,
  },
  {
    code: "bn",
    indictrans_code: "ben_Beng",
    display_name: "Bengali",
    native_name: "বাংলা",
    script: "Bengali",
    enabled: true,
  },
  {
    code: "mr",
    indictrans_code: "mar_Deva",
    display_name: "Marathi",
    native_name: "मराठी",
    script: "Devanagari",
    enabled: true,
  },
  {
    code: "gu",
    indictrans_code: "guj_Gujr",
    display_name: "Gujarati",
    native_name: "ગુજરાતી",
    script: "Gujarati",
    enabled: true,
  },
  {
    code: "kn",
    indictrans_code: "kan_Knda",
    display_name: "Kannada",
    native_name: "ಕನ್ನಡ",
    script: "Kannada",
    enabled: true,
  },
  {
    code: "ml",
    indictrans_code: "mal_Mlym",
    display_name: "Malayalam",
    native_name: "മലയാളം",
    script: "Malayalam",
    enabled: true,
  },
  {
    code: "or",
    indictrans_code: "ory_Orya",
    display_name: "Odia",
    native_name: "ଓଡ଼ିଆ",
    script: "Odia",
    enabled: true,
  },
  {
    code: "pa",
    indictrans_code: "pan_Guru",
    display_name: "Punjabi",
    native_name: "ਪੰਜਾਬੀ",
    script: "Gurmukhi",
    enabled: true,
  },
  {
    code: "as",
    indictrans_code: "asm_Beng",
    display_name: "Assamese",
    native_name: "অসমীয়া",
    script: "Bengali-Assamese",
    enabled: true,
  },
];

export interface UiDictionary {
  askSahayak: string;
  searchPlaceholder: string;
  submit: string;
  sources: string;
  confidence: string;
  newQuestion: string;
  disclaimer: string;
  loadingTitle: string;
  loadingSubtitle: string;
  errorTitle: string;
  knowledgeBase: string;
  aboutPlatform: string;
}

export const UI_DICTIONARY: Record<string, UiDictionary> = {
  en: {
    askSahayak: "Ask Sahayak",
    searchPlaceholder: "e.g., Can I patent an Ayurvedic herbal formulation in India? What NBA approvals are required?",
    submit: "Ask Sahayak",
    sources: "Authoritative Sources",
    confidence: "Confidence",
    newQuestion: "New Question",
    disclaimer: "Legal & Regulatory Disclaimer",
    loadingTitle: "Analyzing Statutory Corpus...",
    loadingSubtitle: "Searching 5,842 statutory chunks across official gazettes and synthesizing grounded guidance.",
    errorTitle: "Query Error",
    knowledgeBase: "Knowledge Base",
    aboutPlatform: "About Platform",
  },
  hi: {
    askSahayak: "सहायक से पूछें",
    searchPlaceholder: "अपना प्रश्न पूछें... (उदा. क्या मैं एक आयुर्वेदिक फॉर्मूलेशन का पेटेंट करा सकता हूं?)",
    submit: "पूछें",
    sources: "प्रामाणिक स्रोत",
    confidence: "विश्वास स्तर",
    newQuestion: "नया प्रश्न",
    disclaimer: "विधिक एवं नियामक अस्वीकरण",
    loadingTitle: "प्रमाणित विधिक संग्रह का विश्लेषण हो रहा है...",
    loadingSubtitle: "IndicTrans2 अनुवाद और Qwen3:8B से साक्ष्य-आधारित मार्गदर्शन तैयार किया जा रहा है।",
    errorTitle: "त्रुटि",
    knowledgeBase: "ज्ञानकोष",
    aboutPlatform: "मंच के बारे में",
  },
  ta: {
    askSahayak: "சகாயக்கிடம் கேளுங்கள்",
    searchPlaceholder: "உங்கள் கேள்வியைக் கேளுங்கள்... (எ.கா. இந்தியாவில் ஆயுர்வேத சூத்திரத்திற்கு காப்புரிமை பெற முடியுமா?)",
    submit: "கேளுங்கள்",
    sources: "அங்கீகரிக்கப்பட்ட ஆதாரங்கள்",
    confidence: "நம்பகத்தன்மை",
    newQuestion: "புதிய கேள்வி",
    disclaimer: "சட்ட மற்றும் ஒழுங்குமுறை மறுப்புரை",
    loadingTitle: "ஆதாரங்களை ஆய்வு செய்கிறது...",
    loadingSubtitle: "IndicTrans2 மொழிபெயர்ப்பு மற்றும் Qwen3:8B மூலம் வழிகாட்டுதல் தயாரிக்கப்படுகிறது.",
    errorTitle: "பிழை",
    knowledgeBase: "அறிவு தளம்",
    aboutPlatform: "இயங்குதளம் பற்றி",
  },
  te: {
    askSahayak: "సహాయక్‌ను అడగండి",
    searchPlaceholder: "మీ ప్రశ్నను అడగండి... (ఉదా. ఆయుర్వేద సూత్రీకరణకు భారతదేశంలో పేటెంట్ పొందవచ్చా?)",
    submit: "అడగండి",
    sources: "ప్రామాణిక ఆధారాలు",
    confidence: "విశ్వసనీయత",
    newQuestion: "కొత్త ప్రశ్న",
    disclaimer: "చట్టపరమైన మరియు నియంత్రణ నిరాకరణ",
    loadingTitle: "చట్టబద్ధమైన ఆధారాలను విశ్లేషిస్తోంది...",
    loadingSubtitle: "IndicTrans2 అనువాదం మరియు Qwen3:8B ద్వారా వివరణ రూపొందించబడుతోంది.",
    errorTitle: "లోపం",
    knowledgeBase: "జ్ఞాన భాండాగారం",
    aboutPlatform: "ప్లాట్‌ఫారమ్ గురించి",
  },
  bn: {
    askSahayak: "সহায়কের কাছে জিজ্ঞাসা করুন",
    searchPlaceholder: "আপনার প্রশ্ন লিখুন... (যেমন: ভারতে আয়ুর্বেদিক ফর্মুলেশনের পেটেন্ট কি সম্ভব?)",
    submit: "জিজ্ঞাসা করুন",
    sources: "অনুমোদিত উৎস",
    confidence: "আত্মবিশ্বাস",
    newQuestion: "নতুন প্রশ্ন",
    disclaimer: "আইনি ও নিয়ন্ত্রক দাবিত্যাগ",
    loadingTitle: "আইনি তথ্য যাচাই করা হচ্ছে...",
    loadingSubtitle: "IndicTrans2 অনুবাদ এবং Qwen3:8B এর মাধ্যমে সঠিক উত্তর তৈরি করা হচ্ছে।",
    errorTitle: "ত্রুটি",
    knowledgeBase: "নলেজ বেস",
    aboutPlatform: "প্ল্যাটফর্ম সম্পর্কে",
  },
  mr: {
    askSahayak: "सहाय्यकाला विचारा",
    searchPlaceholder: "तुमचा प्रश्न विचारा... (उदा. भारतात आयुर्वेदिक फॉर्म्युलेशनचे पेटंट घेता येईल का?)",
    submit: "विचारा",
    sources: "अधिकृत स्रोत",
    confidence: "विश्वास पातळी",
    newQuestion: "नवीन प्रश्न",
    disclaimer: "कायदेशीर आणि नियामक अस्वीकरण",
    loadingTitle: "कायदेशीर माहितीचे विश्लेषण सुरू आहे...",
    loadingSubtitle: "IndicTrans2 भाषांतर आणि Qwen3:8B द्वारे उत्तर तयार केले जात आहे.",
    errorTitle: "त्रुटी",
    knowledgeBase: "ज्ञानकोश",
    aboutPlatform: "प्लॅटफॉर्मबद्दल",
  },
  gu: {
    askSahayak: "સહાયકને પૂછો",
    searchPlaceholder: "તમારો પ્રશ્ન પૂછો... (દા.ત. ભારતમાં આયુર્વેદિક ફોર્મ્યુલેશનનું પેટન્ટ મળી શકે?)",
    submit: "પૂછો",
    sources: "પ્રામાણિક સ્ત્રોતો",
    confidence: "વિશ્વાસ સ્તર",
    newQuestion: "નવો પ્રશ્ન",
    disclaimer: "કાનૂની અને નિયમનકારી ડિસ્ક્લેમર",
    loadingTitle: "કાનૂની માહિતીનું વિશ્લેષણ ચાલુ છે...",
    loadingSubtitle: "IndicTrans2 અનુવાદ અને Qwen3:8B દ્વારા માર્ગદર્શન તૈયાર થઈ રહ્યું છે.",
    errorTitle: "ભૂલ",
    knowledgeBase: "જ્ઞાન ભંડાર",
    aboutPlatform: "પ્લેટફોર્મ વિશે",
  },
  kn: {
    askSahayak: "ಸಹಾಯಕರನ್ನು ಕೇಳಿ",
    searchPlaceholder: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ... (ಉದಾ. ಆಯುರ್ವೇದ ಸೂತ್ರೀಕರಣಕ್ಕೆ ಪೇಟೆಂಟ್ ಪಡೆಯಬಹುದೇ?)",
    submit: "ಕೇಳಿ",
    sources: "ಅಧಿಕೃತ ಮೂಲಗಳು",
    confidence: "ವಿಶ್ವಾಸಾರ್ಹತೆ",
    newQuestion: "ಹೊಸ ಪ್ರಶ್ನೆ",
    disclaimer: "ಕಾನೂನು ಮತ್ತು ನಿಯಂತ್ರಕ ಹಕ್ಕುತ್ಯಾಗ",
    loadingTitle: "ಕಾನೂನು ಮಾಹಿತಿಯ ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ...",
    loadingSubtitle: "IndicTrans2 ಅನುವಾದ ಮತ್ತು Qwen3:8B ಮೂಲಕ ಮಾರ್ಗದರ್ಶನ ರಚಿಸಲಾಗುತ್ತಿದೆ.",
    errorTitle: "ದೋಷ",
    knowledgeBase: "ಜ್ಞಾನ ನೆಲೆ",
    aboutPlatform: "ವೇದಿಕೆಯ ಬಗ್ಗೆ",
  },
  ml: {
    askSahayak: "സഹായകനോട് ചോദിക്കുക",
    searchPlaceholder: "നിങ്ങളുടെ ചോദ്യം ചോദിക്കുക... (ഉദാ. ആയുർവേദ ഫോർമുലേഷന് പേറ്റന്റ് നേടാനാകുമോ?)",
    submit: "ചോദിക്കുക",
    sources: "ആധികാരിക സ്രോതസ്സുകൾ",
    confidence: "വിശ്വാസ്യത",
    newQuestion: "പുതിയ ചോദ്യം",
    disclaimer: "നിയമപരവും നിയന്ത്രണപരവുമായ നിരാകരണം",
    loadingTitle: "വിവരങ്ങൾ വിശകലനം ചെയ്യുന്നു...",
    loadingSubtitle: "IndicTrans2 വിവർത്തനവും Qwen3:8B യും ഉപയോഗിച്ച് ഉത്തരം തയ്യാറാക്കുന്നു.",
    errorTitle: "പിശക്",
    knowledgeBase: "വിജ്ഞാന കേന്ദ്രം",
    aboutPlatform: "പ്ലാറ്റ്‌ഫോമിനെക്കുറിച്ച്",
  },
  or: {
    askSahayak: "ସହାୟକଙ୍କୁ ପଚାରନ୍ତୁ",
    searchPlaceholder: "ଆପଣଙ୍କ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ... (ଯଥା: ଆୟୁର୍ବେଦିକ ଫର୍ମୁଲେସନର ପେଟେଣ୍ଟ ହୋଇପାରିବ କି?)",
    submit: "ପଚାରନ୍ତୁ",
    sources: "ପ୍ରାମାଣିକ ଉତ୍ସ",
    confidence: "ବିଶ୍ୱାସନୀୟତା",
    newQuestion: "ନୂତନ ପ୍ରଶ୍ନ",
    disclaimer: "ଆଇନଗତ ଏବଂ ନିୟାମକ ପ୍ରତ୍ୟାଖ୍ୟାନ",
    loadingTitle: "ଆଇନଗତ ତଥ୍ୟ ବିଶ୍ଳେଷଣ ଚାଲିଛି...",
    loadingSubtitle: "IndicTrans2 ଅନୁବାଦ ଏବଂ Qwen3:8B ଦ୍ୱାରା ମାର୍ଗଦର୍ଶନ ପ୍ରସ୍ତୁତ ହେଉଛି।",
    errorTitle: "ତ୍ରୁଟି",
    knowledgeBase: "ଜ୍ଞାନ ଆଧାର",
    aboutPlatform: "ପ୍ଲାଟଫର୍ମ ବିଷୟରେ",
  },
  pa: {
    askSahayak: "ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ",
    searchPlaceholder: "ਆਪਣਾ ਸਵਾਲ ਪੁੱਛੋ... (ਉਦਾਹਰਣ: ਕੀ ਆਯੁਰਵੈਦਿਕ ਫਾਰਮੂਲੇਸ਼ਨ ਦਾ ਪੇਟੈਂਟ ਕਰਵਾਇਆ ਜਾ ਸਕਦਾ ਹੈ?)",
    submit: "ਪੁੱਛੋ",
    sources: "ਪ੍ਰਮਾਣਿਕ ਸਰੋਤ",
    confidence: "ਵਿਸ਼ਵਾਸ ਪੱਧਰ",
    newQuestion: "ਨਵਾਂ ਸਵਾਲ",
    disclaimer: "ਕਾਨੂੰਨੀ ਅਤੇ ਰੈਗੂਲੇਟਰੀ ਬੇਦਾਅਵਾ",
    loadingTitle: "ਕਾਨੂੰਨੀ ਜਾਣਕਾਰੀ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    loadingSubtitle: "IndicTrans2 ਅਨੁਵਾਦ ਅਤੇ Qwen3:8B ਦੁਆਰਾ ਸੇਧ ਤਿਆਰ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ।",
    errorTitle: "ਗਲਤੀ",
    knowledgeBase: "ਗਿਆਨ ਭੰਡਾਰ",
    aboutPlatform: "ਪਲੇਟਫਾਰਮ ਬਾਰੇ",
  },
  as: {
    askSahayak: "সহায়কক সোধক",
    searchPlaceholder: "আপোনাৰ প্ৰশ্ন সোধক... (উদাহৰণ: আয়ুৰ্বেদিক ফৰ্মুলেচনৰ পেটেণ্ট লব পাৰিনে?)",
    submit: "সোধক",
    sources: "প্ৰামাণিক উৎস",
    confidence: "বিশ্বাসযোগ্যতা",
    newQuestion: "নতুন প্ৰশ্ন",
    disclaimer: "আইনী আৰু নিয়ন্ত্ৰণমূলক অস্বীকৃতি",
    loadingTitle: "তথ্য বিশ্লেষণ কৰা হৈছে...",
    loadingSubtitle: "IndicTrans2 অনুবাদ আৰু Qwen3:8B ৰ দ্বাৰা নিৰ্দেশনা প্ৰস্তুত কৰা হৈছে।",
    errorTitle: "ত্ৰুটি",
    knowledgeBase: "জ্ঞানৰ ভঁৰাল",
    aboutPlatform: "প্লেটফৰ্মৰ বিষয়ে",
  },
};

export function getUiDictionary(langCode?: string): UiDictionary {
  if (!langCode) return UI_DICTIONARY.en;
  return UI_DICTIONARY[langCode.toLowerCase()] || UI_DICTIONARY.en;
}
